<a href="https://colab.research.google.com/github/mahjabeen28/Data-Analytics-using-python-project/blob/main/Arr_operation_day_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print(a + b)
print(a * b)
print(np.sqrt(a))
print(np.sum(a))
print(np.mean(b))

[11 22 33 44 55]
[ 10  40  90 160 250]
[1.         1.41421356 1.73205081 2.         2.23606798]
15
30.0
