<a href="https://colab.research.google.com/github/mahjabeen28/Data-Analytics-using-python-project/blob/main/numpy_arr_day_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

marks = np.array ([50,35,70,65])

print(marks)

[50 35 70 65]


In [ ]:
import numpy as np

students = np.array([
    [70, 45],
    [60, 48],
    [78, 90],
    [50, 80]
])

print(students)

[[70 45]
 [60 48]
 [78 90]
 [50 80]]


In [ ]:
import numpy as np

num = np.array([
    [[3,4],[5,6]],
     [[5,7],[8,7]],
      [[4,2],[3,1]]
    ])
print(num)

[[[3 4]
  [5 6]]

 [[5 7]
  [8 7]]

 [[4 2]
  [3 1]]]
